# Used for publishing to ebay
support_email: 'general@support.lynr.co'
ebay:
  api_url: 'env:EBAY_API_URL'
  sign_in: 'env:EBAY_SIGN_IN'
  devid: 'env:EBAY_DEVID'
  appid: 'env:EBAY_APPID'
  certid: 'env:EBAY_CERTID'
  runame: 'env:EBAY_RUNAME'
# Used to define application level headers
headers:
  "Content-Type": "text/html; charset=utf-8"
librato:
  user: 'foo@example.com'
  token: 'haha fake token'
  source: 'lynrco-spec'
# Used to handle file uploads
transloadit:
  auth_key: '465844d0682711e39bcac1b6747869bc'
  # NOTE: This auth_secret has been regenerated and is no longer valid
  # It is useful only for testing in combination with the fixtures in
  # `spec/lib/lynr/controller/admin_spec.rb`
  auth_secret: 'c889ef8e3d1fd493e85e0f10a1cbd5b6c9f34dad'
