# Used to setting cookies/sessions
domain: 'env:app_domain'
# Used for passing messages between boxes/processes/workers
amqp:
  producer: 'env:AMQP_PRODUCER_URL'
  consumer: 'env:AMQP_CONSUMER_URL'
# Used for publishing to ebay
ebay:
  api_url: 'env:EBAY_API_URL'
  sign_in: 'env:EBAY_SIGN_IN'
  devid: 'env:EBAY_DEVID'
  appid: 'env:EBAY_APPID'
  certid: 'env:EBAY_CERTID'
  runame: 'env:EBAY_RUNAME'
# Used to define application level headers
headers:
  "Content-Type": "text/html; charset=utf-8"
  "Content-Security-Policy": "script-src 'self' https://*"
  "Server": "Lynr.co Application Server"
  "Strict-Transport-Security": "max-age=31536000"
  "X-Content-Type-Options": "nosniff"
  "X-Content-Security-Policy": "script-src 'self' https://*"
  "X-Frame-Options": "DENY"
  "X-Xss-Protection": "1"
# Used by `Lynr::Controller::Legal` to determine current version
legal:
  current: '2014-03-12'
# Used for metrics
librato:
  user: 'env:LIBRATO_USER'
  token: 'env:LIBRATO_TOKEN'
  source: 'env:LIBRATO_SOURCE'
# Used for sending emails
mailgun:
  domain: 'mg.lynr.co'
  from: 'Lynr.co <no-reply@lynr.co>'
  key: 'env:mailgun_api_key'
  url: 'api.mailgun.net/v2'
# Used by Rack::Session::Cookie to encode/decode session information
session:
  secret: 'env:session_secret'
  old_secret: 'env:session_old_secret'
# Used for enabling money transactions with Stripe
stripe:
  key: 'env:stripe_key'
  pub_key: 'env:stripe_pub_key'
  version: '2013-02-13'
  plan: 'env:stripe_plan'
  live: false
# Used to handle file uploads
transloadit:
  auth_key: 'env:transloadit_key'
  auth_secret: 'env:transloadit_secret'
  account_template_id: 'env:transloadit_account_template_id'
  vehicle_template_id: 'env:transloadit_vehicle_template_id'
vin:
  dataone:
    auth_code: 'env:dataone_auth_code'
    client_id: 'env:dataone_client_id'
    url: 'https://api.dataonesoftware.com/webservices/vindecoder/decode'
